<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ShippingService.Domain</AssemblyName>
    <RootNamespace>ShippingService.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\ECommerceOrderProcessing.Shared.csproj" />
  </ItemGroup>

</Project>
