<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>NotificationService.Infrastructure</AssemblyName>
    <RootNamespace>NotificationService.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ECommerceOrderProcessing.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
